### ISSUE TITLE
No tips error trying to classify

### ISSUE THREAD

**Issue by christineolson-ucsf** [biocore/q2-greengenes2#13]
Hello, in trying to use Greengenes2 with a FeatureData[Sequence] object, I get the following error saying "no requested tips found", full error message also attached. Can you please help me resolve this? 
![image](https://user-images.githubusercontent.com/91097042/
![image (1)](https://user-images.githubusercontent.com/91097042/219551001-20eade46-bf85-44f4-8594-7985708d85ed.png)
219550993-ba1f3b3e-fbae-47ab-b22a-b7ab5a86e2d1.png)

**Comment by christineolson-ucsf** [comment]
Other image of command run and initial error: 
![image (2)](https://user-images.githubusercontent.com/91097042/219551110-29f304d1-c4dc-4d1e-9c4e-cb6bf976a635.png)

**Comment by wasade** [comment]
Thanks @christineolson-ucsf! Could you tell me how the `FeatureData[Sequence]` artifact was constructed, and are these 16S V4?

I am very interested in improving the error messages the plugin produces, so I'm hoping to use this github issue to guide a data detection method to better inform users.

**Comment by Ilaria-Pirona** [comment]
I am having the same problem while running _qiime greengenes2 taxonomy-from-table_ (qiime2-2022.8). I am trying to assing the taxonomy to my V3-V4 regions. I followed the tutorial at [link](https://forum.qiime2.org/t/introducing-greengenes2-2022-10/25291/5) and the first command of the section "If you have V4 data" did not raise errors.

**Comment by wasade** [comment]
Hi @Ilaria-Pirona,

What specific primers were used? The majority of the data placed with DEPP are derived from 515F-806R. If your primers are relative to other positions, then it is unlikely your ASVs will be represented. In that scenario, I recommend using the `non-v4-16s` action

**Comment by ebadiea** [comment]
I got the same error "No requested tips found"

**Comment by wasade** [comment]
Thanks, @ebadiea. Can you describe the data, and the commands used?

**Comment by wasade** [comment]
Please reopen if this is still a problem
