### ISSUE TITLE
FTP link in README is broken

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/q2-greengenes2#17]
The readme points to a "current" directory in "greengenes_release" but that leads to a "Forbidden error".

> The following files are provided on the [FTP](http://ftp.microbio.me/greengenes_release/current):

**Comment by wasade** [comment]
Thanks, @ElDeveloper! That is unexpected. The service providing the FTP has been undergoing some revisions related too this [thread](https://forum.qiime2.org/t/greengenes2-classifier-security-error/26187), and I suspect a configuration change disallowed symlinks. The latest version is [2022.10](http://ftp.microbio.me/greengenes_release/2022.10/). I would prefer to keep the README link as is right now as it is a bug in the FTP configuration, and that symlink _should_ be working.

**Comment by ElDeveloper** [comment]
Cheers, thanks for the info! Closing for now as it seems to be working again 👍
