### ISSUE TITLE
What file(s) on the GG2db ftp site can I use as reference-taxonomy for classification by BLAST?

### ISSUE THREAD

**Issue by VoronDM** [biocore/q2-greengenes2#18]
Hi,

What file(s) on the ftp site can I use for classification by BLAST?

qiime feature-classifier classify-consensus-blast 
--i-query "myclusters.qza"
--i-reference-reads _2022.10.seqs.fna.qza_
**--i-reference-taxonomy ???**
--o-classification "output-taxonomy"
--o-search-results "output-taxonomy_blast"

Any from these files?
* 2022.10.taxonomy.asv.tsv.qza
* 2022.10.taxonomy.id.tsv.qza
* 2022.10.taxonomy.md5.tsv.qza

Thanks.

**Comment by wasade** [comment]
I believe this is solved, please reopen if needed

**Comment by VoronDM** [comment]
> I believe this is solved, please reopen if needed

Thank you very much!
