### ISSUE TITLE
Difference in number of ASV when using 2022.10.backbone.full-length.nb.qza and using 2022.10.backbone.full-length.fna.qza ?

### ISSUE THREAD

**Issue by hites77** [biocore/q2-greengenes2#21]
I found more number of ASV when using 2022.10.backbone.full-length.nb.qza file directly in QIIME2 for V3-V4 sequence taxonomy prediction in comparison to using 2022.10.backbone.full-length.fna.qza via greengenes2 plugin. So want to know which way is better than other ?

**Comment by wasade** [comment]
Hi @hites77, 

I apologize for the delay in seeing this. At the moment, I'm primarily monitoring the QIIME 2 forum for questions.

I'm not sure I understand the question. The .nb file is used for taxonomy classification, whereas the .fna file is just the sequences themselves. Could you provide the commands used?

Best,
Daniel

**Comment by hites77** [comment]
Here are the commands:
1. Qiime2 commands using full length nb file
qiime feature-classifier classify-sklearn --i-classifier  amplicon/data/taxonomy/2022.10.backbone.v4.nb.qza --i-reads rep-seqs-dada2.qza --o-classification taxonomy.qza

2. Qiime2 command using greengenes2 plugin
qiime greengenes2 non-v4-16s --i-table table-dada2.qza --i-sequences rep-seqs-dada2.qza --i-backbone 2022.10.backbone.full-length.fna.qza --o-mapped-table table_filtered.gg2.biom.qza --o-representatives rep_seqs_filtered.gg2.fna.qza
qiime greengenes2 taxonomy-from-table --i-reference-taxonomy 2022.10.taxonomy.asv.nwk.qza --i-table table_filtered.gg2.biom.qza --o-classification table_filtered_gg2.taxonomy.qza

**Comment by wasade** [comment]
Hi @hites77, I apologize for the great delay on this. Both results are technically correct, but there are pros/cons to each approach.
