### ISSUE TITLE
How to understand the suffix number of "Rhizobiales_A_501396"? 

### ISSUE THREAD

**Issue by haolilan** [biocore/q2-greengenes2#22]
Hi, I would like to know if the "d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales_A_501396;f__Rhizobiaceae_A_499470" annotated from greengene2 v22.10 is the same as "d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales_A;f__Rhizobiaceae_A" in the GTDB r207.  I have also noticed so many issues that confused me when I wanted to compare 16S rRNA ASVs with shotgun metagenomic data annotated by gtdbtk. Thank you very much!

**Comment by wasade** [comment]
Hi @haolilan, please see the discussion [here](https://forum.qiime2.org/t/introducing-greengenes2-2022-10/25291#interpreting-taxon-labels-11) regarding the labels
