### ISSUE TITLE
Meaning of 6-digit numeric suffix in classification results

### ISSUE THREAD

**Issue by ilnamkang** [biocore/q2-greengenes2#9]
Hi,

I've tried using one of the files on the ftp site for "qiime feature-classifier classify-sklearn" command.

The file I downloaded from the ftp site is "2022.10.backbone.full-length.nb.qza".

This is the qiime command I tried.
\-----
qiime feature-classifier classify-sklearn --i-classifier 2022.10.backbone.full-length.nb.qza --i-reads test.qza --o-classification test_taxonomy.qza --p-n-jobs 72
\-----

Below is the excerpt of the taxonomy string of the result.
\-----
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_**592522**; f__Burkholderiaceae_A_592522
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_592522; f__Burkholderiaceae_A_**592522**; g__Ideonella_A_591966; s__
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_592522; f__Burkholderiaceae_A_592522; g__Limnohabitans_A; s__Limnohabitans_A curvus
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_592522; f__Burkholderiaceae_A_592522; g__Limnohabitans_A; s__Limnohabitans_A curvus
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_592522; f__Burkholderiaceae_A_592522; g__Limnohabitans_A; s__Limnohabitans_A sp001412575
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_592522; f__Burkholderiaceae_A_592522; g__Limnohabitans_A; s__Limnohabitans_A sp001412575
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_592522; f__Burkholderiaceae_A_592522; g__Ottowia_586836
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_**592524**; f__Burkholderiaceae_A_**580492**; g__Polynucleobacter
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_592524; f__Burkholderiaceae_A_580492; g__Polynucleobacter
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales_**597441**; f__Methylophilaceae; g__RFPI01; s__RFPI01 sp009926205
\-----

I'd like to know the meaning of 6-digit numeric suffix (indicated in bold) attached to some taxa names.

Thanks.

Ilnam

**Comment by wasade** [comment]
Hi @ilnamkang, the numeric suffix is a unique label to differentiate clades in the phylogeny. In this case, "o__Burkholderiales" is polyphyletic so in order to produce a unique lineage string based on the phylogeny it is necessary to uniqify the label.

**Comment by ilnamkang** [comment]
Thank you for your clear explanation.

May I ask one more question?

As far as I know, (nearly) all taxa in the GTDB are monophyletic in the genome-based trees constructed by the GTDB team.

Is it possible and maybe not unusual that monophylectic taxa in the GTDB appear polyphyletic in this new Greengenes2 phylogeny?

Thanks.

Ilnam

**Comment by wasade** [comment]
That's a good question! The records may be monophyletic in GTDB, but this is a very different phylogeny and one that includes a broader range of organisms. We do preserve the polyphyletic suffixes that originate from GTDB but we found it was necessary in some instances to introduce our own to ensure the uniqueness of taxon labels.

**Comment by ilnamkang** [comment]
Thank you very much for your clear explanation.

**Comment by wasade** [comment]
You're welcome!
